DROP TABLE IF EXISTS Highscore;
DROP TABLE IF EXISTS Users;

CREATE TABLE Users(
  user_id INTEGER AUTO_INCREMENT,
  username VARCHAR(16) NOT NULL,
  password_hash VARCHAR(50) NOT NULL,
  salt VARCHAR(50) NOT NULL,
  PRIMARY KEY(user_id)
);

CREATE TABLE Highscore(
  score_id INTEGER AUTO_INCREMENT,
  score INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  PRIMARY KEY(score_id),
  FOREIGN KEY(user_id) REFERENCES Users(user_id)
);
